### PR TITLE
Osx arm64 support

### PR DESCRIPTION
**Pull request by mmcauliffe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kylebgorman** [comment]
We can't upgrade yet because the release I just generated needs a single zombie header and my test environment wasn't hermeneutic enough (it had a copy of the old header). So I'm going to fix that next Thursday and then we can upgrade this to 0.3.7post1 or whatever.

**Comment by mmcauliffe** [comment]
Ah gotcha, yeah that sounds good.  Sorry, didn't notice the upgrade PRs for this and Pynini when I was going through the three repos!  Feel free to close the PRs for these if you want to incorporate the arm64 builds into the version upgrade PRs.

**Comment by kylebgorman** [comment]
I think we'll definitely want the MacOS ARM stuff in there too at some
point, though it might be good to bump version first.

K

**Comment by kylebgorman** [comment]
@mmcauliffe if you can merge in the changes in #10, I think this will work.

**Review by kylebgorman — APPROVED** [review]
LGTM

**Pull request merged**
